### ISSUE TITLE
Enhancement Request: support MAC address

### ISSUE THREAD

**Issue by mbierman** [vectronic/homebridge-ping-hosts#18] opened 2022-06-23 23:58 UTC
I am wondering if you would consider supporting MAC addresses as well as IP?

**Comment by mbierman** [comment] 2022-06-24 21:27
So your solution only works with reserved IPs. 

Yes, using something like ARP lookup user could provide mac instead, that would give the current (DHCP) IP and monitoring could work. Not sure this would work between subnets, but for the same subnet is doable I think. See https://github.com/alexgustafsson/homebridge-wol#readme

**Comment by vectronic** [comment] 2022-06-26 19:08
I will try to look into this when I get a chance in the next couple of weeks. I have found a library which should suffice:

https://www.npmjs.com/package/@network-utils/arp-lookup

**Comment by mbierman** [comment] 2022-06-27 10:42
Found this. https://github.com/marcveens/homebridge-device-alive#readme

**Comment by vectronic** [comment] 2022-06-27 10:47
Does https://github.com/marcveens/homebridge-device-alive#readme cover your use case?

**Comment by mbierman** [comment] 2022-06-27 10:54
Sort of. It uses a motion sensor which for what I want isn't my first choice. If ping is successful, it shows motion and then goes off. I get the metpahpor... the ping is motion and until the next ping you don't really know if the device is online.

But most of the time, the device didn't go offline. Most of the time, I prefer a contact or light sensor to a motion sensor. Given that, I prefer your plugin.

A few of my devices use fixed or reserved IPs but it would be nice to have the flexibility of a MAC address so that isn't necessary just for this plugin.

**Comment by mbierman** [comment] 2022-06-29 23:14
Awesome! I'll keep my eyes open for it and happy to do some testing.

**Comment by vectronic** [comment] 2022-07-04 17:11
The published version 3.1.4 seems to do this correctly - kind of.... 

NOTE: This will only resolve an IP address if there is already an entry in the ARP table on the machine running Homebridge.

The problem is that it looks like any solution to populating that table relies on some OS specific native commands... OR... I need to perform a ping to every IP on a configured subnet.... https://superuser.com/questions/29640/inverse-arp-lookup

**Comment by mbierman** [comment] 2022-07-04 18:19
Yeah, I expected there could be an issue for subnets. Maybe have the user specify any subnets they want to scan (CIDR range?) and default to just the subnet that Homebridge is running on?

**Comment by mbierman** [comment] 2022-07-04 21:54
So tried the new build. 

1. A device that is using IP (not mac) is incorrectly showing online. I think this is because, "Sensor is closed on ping success?" doesn't relate well if you choose a Light sensor. (It defaults to on?) Maybe changing the text here or making it conditional on the sensor type ?
2. There's no default sensor type. Probably going to cause a lot of confusion especially for people upgrading. 
3. Sensor types should be a drop down so people don't make typos or try sensor types that aren't supported. 
4. Something could have IPv4, it could have IPv6, but if the user uses mac address perhaps they shouldn't be allowed to enter an IP? There could be conflicts (they set a mac with a DHCP IP and then the IP later changes). In which case, which do you use? At least there should be a warning of some kind to the user to pick IP or Mac in the interface.

**Comment by vectronic** [comment] 2022-08-30 22:50
I've changed the config for items 2 and 3 above. 

I don't quite understand item 1 and don't really have the time to do item 4 at the moment.

Will close this issue now, but feel free to open another if needed.

**Closed by vectronic** 2022-08-30 22:50 UTC
