### ISSUE TITLE
Seems not to work, if pinging a different subnet?

### ISSUE THREAD

**Issue by palasinio** [vectronic/homebridge-ping-hosts#3] opened 2020-06-25 21:54 UTC
Hi, I got this error:
 [PingHosts] [Tunnel] response error: RedirectReceivedError: Redirect received (source=192.168.0.1) for 10.8.0.1 at Thu Jun 25 2020 23:37:28 GMT+0200 (GMT+02:00) with session 254

**Comment by vectronic** [comment] 2020-06-30 12:39
Hi, I will try to look at this next weekend...

**Comment by vectronic** [comment] 2020-07-04 17:15
Looking at the theory behind ICMP redirects: https://www.cisco.com/c/en/us/support/docs/ip/routing-information-protocol-rip/13714-43.html

and docs for the library I'm using: https://github.com/nospaceships/node-net-ping

it looks to me like I'm receiving a RedirectReceivedError from your router, and that indeed the ping has probably reached your intended target on a different subnet.

I will make a change to only error if a RequestTimedOutError occurs or for other errors ONLY if the source of the error matches the ping target.

**Comment by vectronic** [comment] 2020-07-04 17:32
I

**Comment by vectronic** [comment] 2020-07-04 17:34
If there is a chance you could see if the change I did works for you before I publish to npmjs it would be appreciated. You can install the latest by doing:

`npm install -g git://github.com/vectronic/homebridge-ping-hosts.git --unsafe-perm`

instead of

`npm install -g  --unsafe-perm @vectronic/homebridge-ping-hosts`

**Comment by palasinio** [comment] 2020-07-10 20:02
@vectronic , thx for looking into it. There seems to be a little mistake in it now:

`[PingHosts] [Tunnel] socket error with session 229: ReferenceError: err is not defined`

**Comment by vectronic** [comment] 2020-07-10 22:36
Ok - that was a lame copy and paste issue... updated it...

**Comment by palasinio** [comment] 2020-07-17 19:34
Sorry, still not behave as expected:
`[PingHosts] [Tunnel] ignoring response error: RedirectReceivedError: Redirect received (source=192.168.0.1) for 10.8.0.1 at Fri Jul 17 2020 21:17:48 GMT+0200 (GMT+02:00) with session 240`
With a reachable ip of the sam subnet nothing happens.
With an unreachable ip:
`[PingHosts] [Tunnel] ignoring response error: DestinationUnreachableError: Destination unreachable (source=192.168.0.39) for 192.168.0.254 at Fri Jul 17 2020 21:28:40 GMT+0200 (GMT+02:00) with session 286
`

**Comment by vectronic** [comment] 2020-07-19 19:51
I've committed a couple of changes, unfortunately nothing that FIXES the problem.

1. I have changed the default state to OPEN, so that it requires a successful initial ping to CLOSE the sensor. I think that makes more logical and useful sense.

2. I have added a log statement for a successful ping to help with clarity.

3. I've reverted my logic on ignoring errors coming from a source which is different to the target and instead I've opened an issue with ping module I am using to try and understand better what the expected behaviour is and what I should be doing when a `RedirectReceivedError` is received.

Unfortunately I'm not au fait enough to quickly setup a subnet to replicate this myself. I've tried a host-only network VM and a VPN tunnel, but in both cases for an invalid IP I get a `RequestTimedOutError`. For a valid IP on the host-only subnet (i.e. the VM) I didn't get a `RedirectReceivedError` - presumably as there was no router involved.

Could it be that you have two network interfaces where Homebridge is running and it (or this plugin) are using the wrong interface to send the ICMP requests?

**Comment by vectronic** [comment] 2022-08-30 22:48
Hello,

I hit this error https://github.com/vectronic/homebridge-ping-hosts/issues/23 due to a Node upgrade.

I have modified the plugin to no longer rely on the node-net-ping module and therefore the raw-socket module.

Instead I am now using https://github.com/danielzzz/node-ping which makes use of the native platform's ping tool.

Try version 3.2.0 and see how it goes for 

Unfortunately I am hitting this issue currently so can't fully test the new version: https://github.com/vectronic/homebridge-ping-hosts/issues/23

Closing this for now but re-open if you need.

**Closed by vectronic** 2022-08-30 22:48 UTC
